### ISSUE TITLE
Manually typing "/bikes" route throws an error

### ISSUE THREAD

**Issue by veljkovic92** [veljkovic92/freedom-garage#6]

**Comment by CodeShark20xx** [comment]
I took a lot at the console and I'm seeing this error.
![image](https://user-images.githubusercontent.com/92043706/204624885-b2343f86-b352-49dd-bf20-94a647f6dd55.png)

**Comment by CodeShark20xx** [comment]
I added a few console.log() statements and found that the error is indirectly being caused by the avaliableBikes variable being null in the BikeList component.![image](https://user-images.githubusercontent.com/92043706/204628909-cade7fb4-84d4-487d-a893-24a9b0f76a9a.png)

**Comment by CodeShark20xx** [comment]
I haven't learned how to use redux yet, so this one has me beat lol

**Comment by CodeShark20xx** [comment]
I figured out the issue. The fetch() request to get the bike data was still pending when the page loaded. That caused availableBikes to have a null value.  I'm guessing the keys() throws an error due to the null value. After all that happens, then the fetch() request finishes, but the page no longer loads due to the error. I fixed it by adding a null check. With the null check, the page will be blank in the bike list area until the fetch() request finishes.
![image](https://user-images.githubusercontent.com/92043706/204677110-b5b98d13-9064-47fe-acac-52d4bd9048f7.png)

**Comment by veljkovic92** [comment]
@CodeShark20xx Bravo! That fixed it! :) Thanks again for helping me out. That's very nice of you... 🥇

**Comment by veljkovic92** [comment]
@CodeShark20xx fixed it again!

**Comment by CodeShark20xx** [comment]
You're welcome! I'm glad I could help!
